version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: my_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bookapi
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    container_name: my_api
    environment:
      DB_HOST: db
      DB_DATABASE: bookapi
      DB_PORT: 3306
      DB_USERNAME: app
      DB_PASSWORD: password
    volumes:
      - ./api:/var/www/html
    depends_on:
      - db
    ports:
      - "8000:80"

  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    container_name: my_nuxt_client
    environment:
      API_URL: http://localhost:8000
    volumes:
      - ./client:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - api



  nginx:
    image: nginx:latest
    container_name: my_nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./client/dist:/usr/share/nginx/html
      - ./nginx.crt:/etc/nginx/nginx.crt
      - ./nginx.key:/etc/nginx/nginx.key
      
volumes:
  mysql_data:






